/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as NewResearchRouteImport } from './routes/new-research'
import { Route as ResearchJobIdRouteImport } from './routes/research.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const NewResearchRoute = NewResearchRouteImport.update({
  id: '/new-research',
  path: '/new-research',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchJobIdRoute = ResearchJobIdRouteImport.update({
  id: '/research/$jobId',
  path: '/research/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/new-research': typeof NewResearchRoute
  '/research/$jobId': typeof ResearchJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/new-research': typeof NewResearchRoute
  '/research/$jobId': typeof ResearchJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/new-research': typeof NewResearchRoute
  '/research/$jobId': typeof ResearchJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/history' | '/new-research' | '/research/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/history' | '/new-research' | '/research/$jobId'
  id: '__root__' | '/' | '/history' | '/new-research' | '/research/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  NewResearchRoute: typeof NewResearchRoute
  ResearchJobIdRoute: typeof ResearchJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-research': {
      id: '/new-research'
      path: '/new-research'
      fullPath: '/new-research'
      preLoaderRoute: typeof NewResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$jobId': {
      id: '/research/$jobId'
      path: '/research/$jobId'
      fullPath: '/research/$jobId'
      preLoaderRoute: typeof ResearchJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  NewResearchRoute: NewResearchRoute,
  ResearchJobIdRoute: ResearchJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
